name: ml-adv-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - scipy
  - statsmodels
  - plotly
  - tqdm
  - joblib
  - pip
  - pip:
      - ipykernel
      - pgmpy
      - missingno